# docker-compose.yml
version: "3"
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=udapeople-prod
    ports:
      - "5432:5432"
